name: Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
#
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Copy file via scp
#        uses: appleboy/scp-action@master
#        env:
#          HOST: ${{ secrets.SSH_HOST }}
#          USERNAME: ${{ secrets.SSH_USERNAME }}
#          KEY: ${{ secrets.SSH_KEY }}
#        with:
#          source: "."
#          target: "/var/www/html"
#
#      - name: Executing remote  command
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          USERNAME: ${{ secrets.SSH_USERNAME }}
#          KEY: ${{ secrets.SSH_KEY }}
#          script: |
#            echo 'Deployed successfully'


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{Secrets.SSH_HOST}}
          key: ${{Secrets.SSH_KEY}}
          username: ${{Secrets.SSH_USERNAME}}

          script: |
            cd /var/www/html
            git pull -u origin main
            echo 'Deployed successfully'
