name: Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy CERM landing page
        uses: appleboy/ssh-action@master
        with:
          host: ${{Secrets.SSH_HOST}}
          key: ${{Secrets.SSH_KEY}}
          username: ${{Secrets.SSH_USERNAME}}

          script: |
            cd /var/www/html
            git clone git@github.com:mbobiosio/Coming-Soon-Page.git
            echo 'Deployed successfully'