name: Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: scp files
        image: appleboy/drone-scp
        settings:
          host:
            - 174.138.125.228
          username: planetx
          password:
            from_secret: MB01kode*
          port: 22
          command_timeout: 2m
          target: /var/www/html
          source: "."

#      - name: Copy file via scp
#        uses: appleboy/scp-action@master
#        env:
#          host: ${{ secrets.SSH_HOST }}
#          #port: 2478
#          username: ${{ secrets.SSH_USERNAME }}
#          #password: ${{ secrets.SSH_PASSWORD }}
#          KEY: ${{ secrets.SSH_KEY }}
#        with:
#          source: "."
#          target: "/var/www/html"

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          #port: 2478
          username: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
          #password: ${{ secrets.SSH_PASSWORD }}
          script: whoami
          #script: |
          #echo 'Deployed successfully'


#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy CERM landing page
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{Secrets.SSH_HOST}}
#          key: ${{Secrets.SSH_KEY}}
#          username: ${{Secrets.SSH_USERNAME}}
#
#          script: |
#            cd /var/www/html
#            git clone git@github.com:mbobiosio/Coming-Soon-Page.git
#            echo 'Deployed successfully'
